### ISSUE TITLE
wolfsentry_action_get_label() should have a length parameter

### ISSUE THREAD

**Issue by LinuxJedi** [wolfSSL/wolfsentry#6]
New actions are inserted with a length parameter indicating binary labels are possible. `wolfsentry_action_get_label()` only returns the pointer without the length. Recommend either returning a struct that contains pointer or length, or an extra variable to load the length into.

**Comment by LinuxJedi** [comment]
Same with `wolfsentry_event_get_label()`

**Comment by douzzer** [comment]
The returned strings are guaranteed to be null-terminated, and is necessarily short ( <= `WOLFSENTRY_MAX_LABEL_BYTES` i.e. 32 by default), so there doesn't seem to be any need to return the label length on the stack.

If I'm missing something here, please reopen, of course.
